title: SMSBridge
url: https://teesofttech.github.io
baseurl: /SMSBridge
description: Provider-agnostic .NET SDK documentation for sending SMS through multiple providers.
logo: /assets/img/icon.png
theme: jekyll-theme-cayman
show_downloads: false
